{"uuid":"96ac357b-6a68-4ab1-8192-decf658957bb","historyId":"e2ae79d6d9d4abdb0a06aa94803278e9","fullName":"testClasses.loginTest.loginToM2A","labels":[{"name":"package","value":"testClasses.loginTest"},{"name":"testClass","value":"testClasses.loginTest"},{"name":"testMethod","value":"loginToM2A"},{"name":"parentSuite","value":"OpenCart Regression Suite"},{"name":"suite","value":"Login Page Test"},{"name":"subSuite","value":"testClasses.loginTest"},{"name":"host","value":"Anuj"},{"name":"thread","value":"20896@Anuj.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"loginToM2A","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The local appium server has not been started. The given Node.js executable: C:\\Program Files\\nodejs\\node.exe Arguments: [C:\\Appium\\AppiumServer\\Appium-Server-GUI-windows-1.22.3-4\\resources\\app\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --base-path, wd/hub/] \nProcess output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v1.22.3\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m   address: 127.0.0.1\r\n\u001B[35m[Appium]\u001B[39m   basePath: wd/hub/\r\n\u001B[35m[HTTP]\u001B[39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\nFatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1817:16)\n    at listenInCluster (node:net:1865:12)\n    at doListen (node:net:2014:7)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n\n","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\\Program Files\\nodejs\\node.exe Arguments: [C:\\Appium\\AppiumServer\\Appium-Server-GUI-windows-1.22.3-4\\resources\\app\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1, --base-path, wd/hub/] \nProcess output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v1.22.3\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m   address: 127.0.0.1\r\n\u001B[35m[Appium]\u001B[39m   basePath: wd/hub/\r\n\u001B[35m[HTTP]\u001B[39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\nFatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1817:16)\n    at listenInCluster (node:net:1865:12)\n    at doListen (node:net:2014:7)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n\n\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:182)\r\n\tat base.baseClass.setup(baseClass.java:45)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)\r\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 20017 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:147)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:169)\r\n\t... 26 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87)\r\n\t... 28 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1710614203441,"stop":1710614203442}